[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/verify-email"
  to = "/verify-email.html"
  status = 200

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
